configs:
  params:
    server.insecure: true
  cm:
    exec.enabled: true
    statsusage.enabled: true
    statusbadge.enabled: true

controller:
  replicaCount: 3

redis-ha:
  cluster:
    enabled: true

server:
  autoscaling:
    enabled: true
  httproute:
    enabled: true
    parentRefs:
      - name: global-gateway
        namespace: kube-system
        sectionName: https
    hostnames:
      - "argocd.saar-lab.local"
    rules:
      - matches:
          - path:
              type: PathPrefix
              value: /
        backendRefs:
          - name: argocd-server
            port: 80
            weight: 100
  grpcroute:
    enabled: false